name: Keep Render Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:        # Optional: allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          echo "Pinging https://sudharshan-portfolio.onrender.com to keep it awake..."
          curl -s -o /dev/null https://sudharshan-portfolio.onrender.com
          echo "Ping successful!"
